# Generated by Django 4.2.5 on 2023-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'male')], max_length=20, verbose_name='Роль'),
        ),
    ]
