# Generated by Django 4.2.5 on 2023-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('0', 'Производитель'), ('1', 'Покупатель')], max_length=30, verbose_name='Роль'),
        ),
    ]
