# Generated by Django 4.2.5 on 2023-10-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_productlist_options_remove_productlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='author',
            field=models.CharField(default=None, max_length=50, verbose_name='Автор'),
        ),
    ]
